### ISSUE TITLE
Specify name of markdown files should correspond with output object names

### ISSUE THREAD

**Issue by avisionh** [cwthom/shinyhelper#1]
Hi Chris,

_Not quite an issue per se._

I've been trying to implement this and found that unless you name the _<name>.md_ files the same as your _output$<name>_ objects, the helper function could not match the two together. 

Potentially worth making this explicit in your **create_help_file** function and on the _README.md_ file? (Sadly I spent a fair amount of time figuring this out. :( )

Or am I wrong on this?

Thanks,
Avision

**Comment by cwthom** [comment]
From the help file for `?create_help_files`: 

> Description
Helper function to be run interactively - it will initialise a directory of help files (.md files) in
help_dir, using the vector of ids. Pass it a vector of ids corresponding to the inputId and outputId in
your shiny app

I think this is relatively explicit (although factually incorrect in part as it happens, as currently it only creates files in a pre-existing directory, rather than create a new directory). 

I'll see where else I can add this in to make it more obvious how to use the package.

Cheers,
Chris
